# Generated by Django 5.0.3 on 2024-04-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=100)),
                ('maturity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user_type', models.CharField(choices=[('Client', 'Client'), ('Admin', 'Admin'), ('Manager', 'Manager')], default='client', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metabucksapp.baseuser')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referral_code', models.CharField(max_length=100, unique=True)),
                ('seven_day_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_withdrawl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            bases=('metabucksapp.baseuser',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crypto_name', models.CharField(max_length=256)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Referral', 'Referral')], max_length=20)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='metabucksapp.clientuser')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_referred_users', models.PositiveIntegerField(default=0)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_transactions', models.ManyToManyField(blank=True, related_name='referral_trx', to='metabucksapp.transaction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='metabucksapp.clientuser')),
            ],
        ),
        migrations.AddField(
            model_name='clientuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_user', to='metabucksapp.referral'),
        ),
    ]
