# Generated by Django 5.0.3 on 2024-05-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='admin_added_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='admin_maturity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
