# Generated by Django 5.0.3 on 2024-04-06 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='commission_transactions',
        ),
        migrations.AddField(
            model_name='referral',
            name='commission_transactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_trx', to='metabucksapp.transaction'),
        ),
    ]
