# Generated by Django 5.0.3 on 2024-05-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksapp', '0002_baseuser_admin_added_deposit_baseuser_admin_maturity'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='admin_added_withdrawal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
