# Generated by Django 5.0.3 on 2024-04-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksapp', '0002_remove_referral_commission_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Admin', 'Admin'), ('Manager', 'Manager')], max_length=20),
        ),
    ]
