# Generated by Django 5.0.3 on 2024-05-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksapp', '0003_baseuser_admin_added_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='commission_received',
            field=models.BooleanField(default=False),
        ),
    ]
