# Generated by Django 5.0.3 on 2024-05-20 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksapp', '0004_referral_commission_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='metabucksapp.clientuser'),
        ),
    ]
