# Generated by Django 5.0.3 on 2024-05-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksapp', '0005_alter_referral_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
