# Generated by Django 5.0.3 on 2024-04-19 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metabucksapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metabucksapp.baseuser')),
                ('pool_balance', models.PositiveBigIntegerField(default=0)),
                ('payout_balance', models.PositiveBigIntegerField(default=0)),
            ],
            bases=('metabucksapp.baseuser',),
        ),
        migrations.CreateModel(
            name='CommissionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metabucksapp.baseuser')),
                ('pool_balance', models.PositiveBigIntegerField(default=0)),
                ('payout_balance', models.PositiveBigIntegerField(default=0)),
            ],
            bases=('metabucksapp.baseuser',),
        ),
        migrations.CreateModel(
            name='MinimumDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MinimumWithdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_fee', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('withdraw_fee', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('protocol_fee_wallets', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TopAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_text', models.TextField()),
                ('announcement_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletToPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=100)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maturity_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AdminTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crypto_name', models.CharField(max_length=256)),
                ('transaction_type', models.CharField(choices=[('PoolDeposit', 'PoolDeposit'), ('PayoutDeposit', 'PayoutDeposit'), ('Withdrawal', 'Withdrawal')], max_length=20)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='metabucksadmin.adminuser')),
            ],
        ),
    ]
