# Generated by Django 5.0.3 on 2024-04-03 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crypto_name', models.CharField(max_length=256)),
                ('transaction_type', models.CharField(choices=[('PoolDeposit', 'PoolDeposit'), ('PayoutDeposit', 'PayoutDeposit'), ('Withdrawal', 'Withdrawal')], max_length=20)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='metabucksadmin.adminuser')),
            ],
        ),
    ]
