# Generated by Django 5.0.3 on 2024-05-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletToPool',
        ),
    ]
