# Generated by Django 5.0.3 on 2024-05-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksadmin', '0002_delete_wallettopool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
