# Generated by Django 5.0.3 on 2024-04-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksadmin', '0003_profitupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitupdate',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
