# Generated by Django 5.0.3 on 2024-04-06 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksadmin', '0005_commissionupdate_minimumdeposit_minimumwithdraw_and_more'),
        ('metabucksapp', '0003_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metabucksapp.baseuser')),
                ('pool_balance', models.PositiveBigIntegerField(default=0)),
                ('payout_balance', models.PositiveBigIntegerField(default=0)),
            ],
            bases=('metabucksapp.baseuser',),
        ),
    ]
