# Generated by Django 5.0.3 on 2024-04-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksadmin', '0006_manageruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='payout_balance',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='pool_balance',
        ),
        migrations.RemoveField(
            model_name='manageruser',
            name='payout_balance',
        ),
        migrations.RemoveField(
            model_name='manageruser',
            name='pool_balance',
        ),
    ]
