# Generated by Django 5.0.3 on 2024-04-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksadmin', '0007_remove_adminuser_payout_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='payout_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='pool_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manageruser',
            name='payout_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manageruser',
            name='pool_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
