# Generated by Django 5.0.3 on 2024-04-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabucksadmin', '0008_adminuser_payout_balance_adminuser_pool_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionupdate',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='minimumdeposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AlterField(
            model_name='minimumwithdraw',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AlterField(
            model_name='protocolfee',
            name='deposit_fee',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='protocolfee',
            name='withdraw_fee',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
    ]
